SiaFoundation/walletd

- .github/workflows/publish.yml
Signs Windows releases to satisfy Windows smart screen.
> Sign windows releases

- cmd/walletd/main.go
check() already calls log.Fatal if err != nil, so this code is redundant
> Remove unreachable code

- persist/sqlite/consensus.go
- persist/sqlite/consensus_test.go
- persist/sqlite/init.sql
- persist/sqlite/wallet.go
- wallet/update.go
- wallet/wallet.go
Fixes a few panics during reorgs
> Fix reorg balance

- api/api_test.go
- api/client.go
- api/server.go
Fixes the return type of `client.Wallets()` and fixes the `[POST] /wallets` request
> Fix wallet client

- cmd/walletd/main.go
- persist/sqlite/consensus.go
- persist/sqlite/consensus_test.go
- persist/sqlite/init.sql
- persist/sqlite/wallet_test.go
- wallet/update.go
- Fixes duplicate elements when resubscribing
- Moves balance tracking back into the store for future optimizations
- Removes the need to store intermittent update state in memory
> Fix duplicate elements during resubscribe

- api/api_test.go
- api/client.go
- api/server.go
- persist/sqlite/addresses.go
- wallet/addresses.go
- wallet/manager.go
Adds endpoints for interacting with single addresses. These are primarily useful for index mode, where the consumer fully manages the state, like Sia Central's lite wallet.
> Add single address endpoints

- .gitignore
- persist/sqlite/consensus.go
- persist/sqlite/sql.go
- wallet/wallet_test.go
> Fix SiaFund support in SQLite

- persist/sqlite/addresses.go
- persist/sqlite/consensus.go
- persist/sqlite/init.sql
- persist/sqlite/wallet.go
- wallet/update.go
This PR removes the `chain_indices` table. I'm not entirely sure that's what we want but since we were discussing getting rid of the `CASCADE` deletes I don't see a good reason to keep the table. Creating it and linking it is more of a nuisance than anything else imo, if you don't get the upside of the cascaded deletes.
I hit an interesting test failure in the process, an underflow is triggered in `TestEphemeralBalance` which is interesting because on `master` there are no orphaned indices, but now there are orphaned `siacoin_elements`... so I'm a little bit puzzled still on why that is. 
I think there might also be a bug in `RevertOrphans` because we loop over the orphaned indices and it seems we only deal with the balances of the last orphan. (consensus.go:751) Since I'm not sure …
> Remove `chain_indices` table

- wallet/wallet.go
- wallet/wallet_test.go
This changes the `wallet.Event` JSON serialization to match the Go struct. Unfortunately, this will break the UI again @alexfreska.
- Adds the `maturityHeight` field. The UI should use this to distinguish between received-but-not-spendable payouts (maybe lower the opacity or add a "lock" icon).
- Changes the `val` field to `data` to match the rest of `walletd`.
```json
{
"id": "h:13271ead1070290c9cbe39ed7a15aa1107a27029479858ee9ab2fcc237ed4aa0",
"timestamp": "2024-05-01T11:35:03Z",
"index": {
"height": 68278,
"id": "bid:000000009db92b8834aed7809ebe3ff0184e632e8333bba3802de8cd10d2fc86"
},
"maturityHeight": 68423,
"relevant": [
"addr:11d68c52e67a800d0ca99867e410cfa9c0c3f5bc1726aa90e88f40b7ad0825c91841904dae10"
],
"type": "contract payout",
"data": {...}
}
> Fix event serialization

- api/api.go
- api/api_test.go
- api/server.go
- cmd/walletd/main.go
- cmd/walletd/node.go
- persist/sqlite/addresses.go
- persist/sqlite/consensus.go
- persist/sqlite/init.go
- persist/sqlite/init.sql
- persist/sqlite/peers_test.go
- persist/sqlite/store.go
- persist/sqlite/wallet.go
- wallet/manager.go
- wallet/options.go
- wallet/update.go
- wallet/wallet_test.go
Adds "Full" and "None" indexing modes. The indexing mode can only be set once and cannot be changed since it changes how the state tree is stored.
"Partial" is the default. It only stores the state and events for addresses that are connected to a wallet.
"Full" will store the entire state of the blockchain regardless of addresses loaded into the wallet. It will also throw an error if the user attempts to trigger a scan with `/wallet/scan` 
"None" will not process chain updates and treat the chain state as read-only. This isn't particularly useful now, but it will be nice when networked databases are supported.
> Add "full" and "none" indexing modes

- persist/sqlite/consensus.go
- persist/sqlite/wallet.go
- wallet/manager.go
- wallet/wallet.go
- wallet/wallet_test.go
Removes the `eventData` interface and the custom json encoding in favor of a field on the Event struct. This does remove the limited guarantees we have about the data aligning with the type, but in practice its not a significant enough downside to justify the custom marshalling.
~~@alexfreska this will break the UI... Again..~~ Actually, it will not
```json
{
"id": "h:a0f44763dbb2d2f95eec0f20f18bda75e7026297b6172f73449f3c3d67c2099c",
"index": {
"height": 997,
"id": "bid:000000004d7b155547e163ea4933c28cf2171c43c0c02e50c04f6718f6af37f0"
},
"timestamp": "2023-01-16T02:06:49Z",
"maturityHeight": 997,
"relevant": null,
"type": "transaction",
"data": {
"siacoinInputs": [
{
"id": "h:35b81e41f594d7faeb88bd8eaac2eaa68ce99fe1c8fe5f0cba8fafa65ab3a70e",
"leafIndex": 0,
"merkleProof": null, …
```
> Add Type field for wallet events 

- api/server.go
- persist/sqlite/events.go
- wallet/manager.go
- wallet/wallet_test.go
Adds a new endpoint `/api/events/:id` to get an event by its ID. This is primarily only useful when running in full index mode to lookup arbitrary transactions.
> Add events endpoint

- persist/sqlite/addresses.go
- persist/sqlite/init.sql
- persist/sqlite/migrations.go
- persist/sqlite/wallet.go
Forces the wallet and address event queries to use the proper index since the query planner did not want to select it automatically. This significantly improves performance for wallets with lots of events.
> Improve wallet and address event query performance

- persist/sqlite/addresses.go
- persist/sqlite/consensus_test.go
- persist/sqlite/wallet.go
- wallet/addresses.go
- wallet/manager.go
- wallet/wallet_test.go
Ran into an issue with the UI trying to spend an immature UTXO. I don't believe there's a reason to make the UI filter the UTXO list, so I changed the endpoints to only include matured UTXOs.
> Change Siacoin endpoints to only include matured UTXOs

- go.mod
- go.sum
- persist/sqlite/addresses.go
- persist/sqlite/wallet.go
- wallet/update.go
- wallet/wallet.go
- https://github.com/SiaFoundation/coreutils/pull/65
- https://github.com/SiaFoundation/core/pull/174
> Update for core and coreutils changes

- persist/sqlite/init.sql
- persist/sqlite/migrations.go
- persist/sqlite/wallet.go
`/wallet/:id/events` can be slow in full index mode when the wallet has no events. Adds a check to make sure the wallet has events before running the more expensive events query.
> Improve wallet events performance

- api/server.go
- persist/sqlite/encoding.go
- persist/sqlite/peers_test.go
- persist/sqlite/utxo.go
- wallet/manager.go
- wallet/wallet_test.go
Adds two new endpoints `/outputs/siacoin/:id` and `/outputs/siafund/:id` to lookup utxos by ID. These endpoints are intended only for nodes in `full` index mode.
> Add output endpoint

- README.md
- api/api_test.go
- api/server.go
- cmd/walletd/main.go
- cmd/walletd/node.go
- config/config.go
Adds a config option and CLI flag to disable auth on some endpoints when running `walletd` as a service. This option is intended to make it easier for wallet developers and exchanges to use `walletd` as part of their infrastructure.
**`walletd.yml`:**
```yml
http:
publicEndpoints: true
```
**CLI flag:**
```bash
walletd --http.public
```
> Add public endpoints

- persist/sqlite/consensus.go
- wallet/manager.go
- wallet/wallet_test.go
Fixes a panic that occurs when the consensus database is deleted and the node is attempting to sync. This will remove all existing consensus state from the database and rescan from genesis without affecting the wallet data.
Fixes #204
> fix: Fix panic when resyncing after consensus database is deleted

- .changeset/log_startup_errors_to_stderr.md
- cmd/walletd/config.go
- cmd/walletd/main.go
- cmd/walletd/miner.go
Makes it easier for scripts to parse startup issues
Fixes #203
> Log startup errors to stderr

- wallet/update.go
- wallet/wallet.go
- wallet/wallet_test.go
Changes the indexer to skip Siafund claim events and UTXOs with zero value since they do not affect the wallet. This is inline with the indexing behavior of transactions that do not spend or create UTXOs.
> Skip indexing zero-valued Siafund claim events

- .changeset/add_transaction_construction_api.md
- api/api.go
- api/api_test.go
- api/client.go
- api/server.go
- cmd/walletd/miner.go
- wallet/manager.go
Adds two new endpoints to construct transactions. This combines and simplifies the existing fund flow for sending siacoin and siafund transactions.
Requires #210
> Construct Transaction API

- .changeset/added_a_test_for_migrations_to_ensure_consistency_between_database_schemas.md
- persist/sqlite/init.go
- persist/sqlite/migrations_test.go
- persist/sqlite/store.go
Refactors migrations to have one migration per transaction and adds a test to ensure schema consistency between migrations.
> Add migration test

- .changeset/add_merkle_proof_basis_to_utxo_api_responses.md
- api/api.go
- api/api_test.go
- api/client.go
- api/server.go
- persist/sqlite/addresses.go
- persist/sqlite/store.go
- wallet/addresses.go
- wallet/manager.go
- wallet/wallet_test.go
Changes the response to include the Merkle proof basis for the following endpoints. The basis is required when broadcasting v2 transactions.
- `[GET] /addresses/:address/outputs/siacoin`
- `[GET] /addresses/:address/outputs/siafund`
- `[GET] /wallets/:id/outputs/siacoin`
- `[GET] /wallets/:id/outputs/siafund`
```json
{
"basis": {
"height": 1,
"id": "f362385eea61f81627f283a31af9faf6417fbb88d53b794639a34e18515996e9"
},
"outputs": [
{
"id": "ed556177482e70822a5dcad9343efb51998425884788415349bef8eba7e063ae",
"stateElement": {
"leafIndex": 3,
"merkleProof": [
"01048fc792904f156844a5524671304d3a020861da144afa4acc6553db63c1fd",
"33efdfaf9bb212842292ab6f298c454e1b3d412aa7beb7efdccdfccf09f5b4ee",
"102345919e408540d240460b0d84aa2f6da9a3d8f74765fd7c6daae6e46dd7f3"
]
},
"siacoinOutput": {
"value": …
```
> Add Merkle Proof Basis 

- persist/sqlite/addresses.go
- persist/sqlite/consensus.go
- persist/sqlite/events.go
- persist/sqlite/events_test.go
- persist/sqlite/init.sql
- persist/sqlite/migrations.go
- persist/sqlite/wallet.go
- wallet/manager.go
The current event queries are optimized for addresses with a large number of events. When an address has a small number of events, queries take an extremely long time to complete.
```
QUERY PLAN
|--SCAN ev USING INDEX events_maturity_height_id_idx
|--SEARCH ci USING INTEGER PRIMARY KEY (rowid=?)
|--SEARCH ea USING COVERING INDEX event_addresses_event_id_address_id_idx (event_id=?)
--SEARCH wa USING COVERING INDEX sqlite_autoindex_wallet_addresses_1 (wallet_id=? AND address_id=?)
```
Removing the forced index allows queries for a small number of events to complete quickly, but fails for a large number due to the temp b-tree sort.
```
QUERY PLAN
|--SEARCH sa USING COVERING INDEX sqlite_autoindex_sia_addresses_1 (sia_address=?)
|--SEARCH ea USING INDEX event_addresses_address_id_idx …
```
> Events performance

- api/api_test.go
- api/server.go
There was a change in coreutils that makes it so the zero value of spend policy cannot be encoded or decoded. This changes the construction API to return an error if one of the funding addresses does not have a policy set.
> api: disable construction API if spend policy is unset

- .changeset/add_spent_element_endpoints.md
- api/api.go
- api/api_test.go
- api/client.go
- api/server.go
- persist/sqlite/consensus.go
- persist/sqlite/init.sql
- persist/sqlite/migrations.go
- persist/sqlite/utxo.go
- wallet/manager.go
- wallet/update.go
Added two new endpoints `[GET] /outputs/siacoin/:id/spent` and `[GET] /outputs/siafund/:id/spent`. 
These endpoints will return a boolean, indicating whether the UTXO was spent, and the transaction it was spent in. These endpoints are designed to make verifying atomic swaps easier. It is an acceptable limitation that spent utxos are only kept for 144 blocks and will return a 404 afterwards. This may be changed in a follow up.
````
$ curl http://localhost:9980/api/outputs/siacoin/9b89152bb967130326702c9bfb51109e9f80274ec314ba58d9ef49b881340f2f/spent
{
spent: true,
event: ...
}
```
> Add spent UTXO endpoints

- .changeset/add_endpoint_to_check_for_addresses_that_have_been_seen_on_chain.md
- api/api.go
- api/client.go
- api/server.go
- persist/sqlite/address_test.go
- persist/sqlite/addresses.go
- wallet/addresses.go
- wallet/manager.go
Adds `[POST] /check/addresses` to check for addresses that have been seen on chain. This endpoint is useful for scanning the chain for look-aheads when in full index mode
> add check endpoint

- .changeset/add_get_consensusstateid_endpoint_to_return_the_block_and_its_consensus_state.md
- api/api.go
- api/api_test.go
- api/client.go
- api/server.go
Adds an endpoint to fetch a block and its state. Useful when scanning the blockchain to determine height of v1 blocks.
> Add consensus state

- .changeset/changed_all_endpoints_that_to_return_siacoin_or_siafund_elements_to_also_return_the_number_of_confirmations.md
- api/api_test.go
- api/client.go
- api/server.go
- persist/sqlite/wallet.go
- wallet/manager.go
- wallet/wallet_test.go
Changed all endpoints that to return Siacoin or Siafund elements to also return the number of confirmations
```json
{
{
"id": "5fb7f9ef38dfeeeb4d8c0c1f105452511f0e966dec1ce545e490f5eee46d166f",
"stateElement": {
"leafIndex": 25490,
"merkleProof": [
"9175d0ea4dbdecd0517bd275afd98250438193429d0dc7493672217464f3bfa3",
"ab87ecba97723b67e42027dd8d2ad5a51ab48c3cd1b38dc461805b266b1fa728",
"6cb7dcc6300e8344b17012b36fe64a0d7e1678d54736d1fd910c7c9665b273b9"
]
},
"siacoinOutput": {
"value": "344000",
"address": "000000000000000000000000000000000000000000000000000000000000000089eb0d6a8a69"
},
"maturityHeight": 7437,
"confirmations": 6
}
}
```
> Return confirmations

- .changeset/fixed_a_panic_when_listening_to_localhost_on_some_windows_11_systems.md
- cmd/walletd/node.go
Some Windows systems no longer recognize `localhost`. This adds a fallback for these systems instead of failing to start.
> Fix localhost panic

- .changeset/add_batch_endpoint_to_allow_adding_multiple_addresses_to_a_wallet_at_a_time.md
- api/api_test.go
- api/client.go
- api/server.go
- persist/sqlite/address_test.go
- persist/sqlite/consensus_test.go
- persist/sqlite/events_test.go
- persist/sqlite/wallet.go
- persist/sqlite/wallet_test.go
- wallet/manager.go
- wallet/wallet_test.go
This PR adds a batch endpoint that allows batch adding addresses to a wallet. It's a little unfortunate because the current endpoint is `PUT /wallets/:id/addresses` ... leaving little room for a neat batch endpoint. I considered making it so the current endpoint allows both a single and multiple addresses, but seems like a worse solution. I ended up adding `/wallets/:id/addresses/batch`, which allows adding 1000 addresses at a time. I tried keeping the loc to a minimum by just looping over the addresses and using a variadic parameter where possible.
> Allow adding addresses in batch
